services:
  node0:
    platform: linux/amd64
    container_name: she-node-0
    image: "she-chain/localnode"
    user: "${USERID}:${GROUPID}"
    ports:
      - "26656-26658:26656-26658"
      - "9090-9091:9090-9091"
      - "8545-8546:8545-8546"
    environment:
      - ID=0
      - CLUSTER_SIZE=4
      - NUM_ACCOUNTS
      - SKIP_BUILD
      - INVARIANT_CHECK_INTERVAL
      - UPGRADE_VERSION_LIST
    volumes:
      - "${PROJECT_HOME}:/she-protocol/she-chain:Z"
      - "${GO_PKG_PATH}/mod:/root/go/pkg/mod:Z"
      - "${GOCACHE}:/root/.cache/go-build:Z"
    networks:
      localnet:
        ipv4_address: 192.168.10.10

  node1:
    platform: linux/amd64
    container_name: she-node-1
    image: "she-chain/localnode"
    user: "${USERID}:${GROUPID}"
    ports:
      - "26659-26661:26656-26658"
      - "9092-9093:9090-9091"
    environment:
      - ID=1
      - CLUSTER_SIZE=4
      - NUM_ACCOUNTS
      - SKIP_BUILD
      - INVARIANT_CHECK_INTERVAL
      - UPGRADE_VERSION_LIST
    volumes:
      - "${PROJECT_HOME}:/she-protocol/she-chain:Z"
      - "${PROJECT_HOME}/../she-tendermint:/she-protocol/she-tendermint:Z"
      - "${PROJECT_HOME}/../she-cosmos:/she-protocol/she-cosmos:Z"
      - "${PROJECT_HOME}/../she-db:/she-protocol/she-db:Z"
      - "${PROJECT_HOME}/../go-ethereum:/she-protocol/go-ethereum:Z"
      - "${GO_PKG_PATH}/mod:/root/go/pkg/mod:Z"
      - "${GOCACHE}:/root/.cache/go-build:Z"
    networks:
      localnet:
        ipv4_address: 192.168.10.11

  node2:
    platform: linux/amd64
    container_name: she-node-2
    image: "she-chain/localnode"
    user: "${USERID}:${GROUPID}"
    environment:
      - ID=2
      - CLUSTER_SIZE=4
      - NUM_ACCOUNTS
      - SKIP_BUILD
      - INVARIANT_CHECK_INTERVAL
      - UPGRADE_VERSION_LIST
    ports:
      - "26662-26664:26656-26658"
      - "9094-9095:9090-9091"
    volumes:
      - "${PROJECT_HOME}:/she-protocol/she-chain:Z"
      - "${PROJECT_HOME}/../she-tendermint:/she-protocol/she-tendermint:Z"
      - "${PROJECT_HOME}/../she-cosmos:/she-protocol/she-cosmos:Z"
      - "${PROJECT_HOME}/../she-db:/she-protocol/she-db:Z"
      - "${PROJECT_HOME}/../go-ethereum:/she-protocol/go-ethereum:Z"
      - "${GO_PKG_PATH}/mod:/root/go/pkg/mod:Z"
      - "${GOCACHE}:/root/.cache/go-build:Z"
    networks:
      localnet:
        ipv4_address: 192.168.10.12

  node3:
    platform: linux/amd64
    container_name: she-node-3
    image: "she-chain/localnode"
    user: "${USERID}:${GROUPID}"
    environment:
      - ID=3
      - CLUSTER_SIZE=4
      - NUM_ACCOUNTS
      - SKIP_BUILD
      - INVARIANT_CHECK_INTERVAL
      - UPGRADE_VERSION_LIST
    ports:
      - "26665-26667:26656-26658"
      - "9096-9097:9090-9091"
    volumes:
      - "${PROJECT_HOME}:/she-protocol/she-chain:Z"
      - "${PROJECT_HOME}/../she-tendermint:/she-protocol/she-tendermint:Z"
      - "${PROJECT_HOME}/../she-cosmos:/she-protocol/she-cosmos:Z"
      - "${PROJECT_HOME}/../she-db:/she-protocol/she-db:Z"
      - "${PROJECT_HOME}/../go-ethereum:/she-protocol/go-ethereum:Z"
      - "${GO_PKG_PATH}/mod:/root/go/pkg/mod:Z"
      - "${GOCACHE}:/root/.cache/go-build:Z"
    networks:
      localnet:
        ipv4_address: 192.168.10.13

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
